### ISSUE TITLE
filesystem error

### ISSUE THREAD

**Issue by nicodinh** [nicodinh/pm2#1]
```bash
PM2][WARN] Applications api not running, starting...
/home/nico/.nvm/versions/node/v7.4.0/lib/node_modules/pm2/lib/API.js:1004
        Common.printOut(conf.PREFIX_MSG + 'App [%s] launched (%d instances)', data[0].pm2_env.name, data.length);
                                                                                     ^

TypeError: Cannot read property 'pm2_env' of undefined
    at /home/nico/.nvm/versions/node/v7.4.0/lib/node_modules/pm2/lib/API.js:1004:86
    at /home/nico/.nvm/versions/node/v7.4.0/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/client.js:45:10
    at Parser.<anonymous> (/home/nico/.nvm/versions/node/v7.4.0/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/req.js:67:8)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Parser._write (/home/nico/.nvm/versions/node/v7.4.0/lib/node_modules/pm2/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at Parser.Writable.write (_stream_writable.js:245:11)
    at Socket.ondata (_stream_readable.js:555:20)

  post-deploy hook failed

Deploy failed
```

**Comment by nicodinh** [comment]
parcequ'il a pas les droit sur le dossier definis dans le chemin du error_file et out_file
